##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - autoconf
    - automake
    - autotools-dev
    - autopoint
    - binutils-dev #make check/distcheck
    - clang
    - clang-tools
    - cppcheck
    - debhelper
    - git
    - kdelibs-bin #make check/distcheck
    - libboost-dev
    - libboost-system-dev
    - libcrypto++-dev
    - libgd-dev
    - libgeoip-dev
    - libglib2.0-dev
    - libpng-dev
    - libqt4-dev #make check/distcheck
    - libqt4-dev-bin #make check/distcheck
    - libreadline-dev
    - libupnp-dev
    - libwxbase3.0-dev #sid
#   - libwxgtk3.0-dev #buster
    - libwxgtk3.0-gtk3-dev
    - pastebinit
    - wx3.0-i18n
    - zlib1g-dev

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--prefix=/usr --mandir=\$${prefix}/share/man --infodir=\$${prefix}/share/info --disable-dependency-tracking --disable-ccache --disable-debug --enable-amule-daemon --enable-amulecmd --enable-ed2k --enable-webserver --enable-amule-gui --enable-cas --enable-wxcas --enable-alc --enable-alcc --disable-embedded-crypto --enable-geoip --enable-upnp --with-denoise-level=0 --with-boost'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
