##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - autoconf
    - automake
    - autotools-dev
    - autopoint
    - debhelper
    - git
    - libboost-dev
    - libboost-system-dev
    - libcrypto++-dev
    - libgd-dev
    - libgeoip-dev
    - libglib2.0-dev
    - libpng-dev
    - libreadline-dev
    - libupnp-dev
    - libwxbase3.0-dev #sid
#    - libwxgtk3.0-dev #sid
    - libwxgtk3.0-gtk3-dev
    - pastebinit
    - wx3.0-i18n
    - zlib1g-dev

variables:
  - AMULE_VERSION="2.3.2+git20200530.3a77afb-1_amd64.deb"
  - AMULE_VERSION_ALL="2.3.2+git20200530.3a77afb-1_all.deb"

build_scripts:
  - rm -R debian
  - mkdir debgit
  - cd debgit
  - git clone --depth 1 https://salsa.debian.org/debian/amule &> /dev/null
  - cd ..
  - cp -dpR ./debgit/amule/debian/ .
  - egrep -lRZ '# Configure arguments' . | xargs -0 -l sed -i -e 's/# Configure arguments/export DEB_CFLAGS_MAINT_APPEND  = -Wall -Woverloaded-virtual -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Werror=format-security/g'
  - rm debian/patches/*
  - egrep -lRZ 'libwxgtk3.0-dev' . | xargs -0 -l sed -i -e 's/libwxgtk3.0-dev/libwxgtk3.0-gtk3-dev/g'
  - ./gtk3buildPackages.sh $CPU_COUNT
  - cd ..
  - curl -F file=@amule_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-utils-gui_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-utils-gui-dbgsym_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-dbgsym_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-daemon_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-utils_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-daemon-dbgsym_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-utils-dbgsym_$AMULE_VERSION -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-common_$AMULE_VERSION_ALL -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
  - curl -F file=@amule-gnome-support_$AMULE_VERSION_ALL -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
