dist: bionic
language: shell
os: linux
services:
  - docker
addons:
  apt:
    packages:
      - python3-github

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .build.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .build.yml --build scripts

env:
#  - DISTRO="archlinux:latest"
  - DISTRO="debian:buster"
#  - DISTRO="fedora:latest"
#  - DISTRO="ubuntu:devel"
